import os

env_options = {
    "CC"    : "arm-linux-gnueabihf-gcc",
    "CXX"   : "arm-linux-gnueabihf-g++",
    "LD"    : "arm-linux-gnueabihf-g++",
    "AR"    : "arm-linux-gnueabihf-ar",
    "STRIP" : "arm-linux-gnueabihf-strip",
    "PATH"  : os.environ['PATH'],
	"CCFLAGS" : ['-pedantic','-std=c11','-g','-Wall','-D_GNU_SOURCE'],
	"LINKFLAGS" : ['-Wall','-lrt','-lpthread','-lm'],
	"CPPPATH": ['./pigpio','./libzmq-master/include','.']
}

env = Environment(**env_options)

env['ENV']['TERM'] = os.environ['TERM']

srcs = ['app.c','hw.c','phy.c','rf_app.c','rf_hw.c','buf_io.c','cmng.c','cbf.c','app_cmng.c', 'ini.c']
incs = []

env.Program('fwl_hub',srcs,incs,LIBS=['pigpio', '-lzmq.a'],LIBPATH=['./pigpio','-Luser/local/lib'])

